#-------------
# Site Setting
#-------------
title: Ahmad Blog
first_name: Ahmad
middle_name: Nur
last_name: 
email: ahmadnursahid12345@gmail.com
description:
home_title:
  Hello 👋 <br> 
  I'm <span>Ahmad nur</span> <br> 
  Mahasiswa Institut Teknologi Garut
profile_picture: profile_pict.jpg

footer_text: >-
  ""

baseurl: ""
url: "ahmaadn.github.io"

latest_update: true
icon: logo.svg

#-------------
# Sosial
#-------------

sosial:
  github      : ahmaadn
  facebook    : a.ahmad415
  instagram   : a.ahmaadn

# Build settings
plugins:
  - jekyll-feed
  - jekyll_picture_tag
  - jekyll-archives
  - jekyll-paginate-v2
  # - jekyll-tabs
  - jemoji

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archives
    tag: archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Blog
permalink: /blog/:year/:month/:day/:title/
sosial_navbar: True

# Pagination
pagination:
  enabled: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

default:
  - scope:
      path: "assets/**/*.*"
    values:
      sitemap: false

sass:
  sass_dir: _sass
  style: compressed

picture:
  source: "assets/img"
  output: "assets/img/generated"
