title: Ahmaadn
first_name: Ahmad
middle_name: nur
last_name: sahid
email: ahmadnursahid12345@gmail.com
description: Inspirasi dan wawasan untuk hidup yang lebih baik.
home_text: >
  Hello 👋 <br> 
  I'm <span>Ahmad nur</span> <br> 
  Selamat datang di blog
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank"> Jekyll </a> • Hosted by <a herf='https://www.netlify.com/' target='_blank'>Netlify</a>

profile_picture: profile_pict.jpg


keywords: blog, tutorial, ahmmadn, ahmadnur

lang: id
icon: logo.svg

url: "ahmaadn.github.io"
baseurl: ""

sosial_navbar: True
permalink: /blog/:title/

# Sosial
sosial:
  github      : ahmaadn
  facebook    : a.ahmad415
  instagram   : a.ahmaadn

plugins:
  - jekyll-feed
  - jekyll_picture_tag
  - jekyll-archives
  - jekyll-paginate-v2
  - jemoji

default:
  - scope:
      path: "assets/**/*.*"
    values:
      sitemap: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .vscode
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archives
    tag: archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

pagination:
  enabled: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

sass:
  sass_dir: _sass
  style: compressed

picture:
  source: "assets/img"
  output: "assets/img/generated"


comments:
  # 'disqus' / 'giscus' / 'utterances' are available
  provider: giscus


giscus:
  repo:                "ahmaadn/ahmaadn.github.io"
  repo-id:             "R_kgDOIrGDhg"
  category:            "Comments"
  category-id:         "DIC_kwDOIrGDhs4CUyFB"
  mapping:             "pathname"
  reaction-enabled:    "1"
  data-emit-metadata:  "0"
  theme:               "light"
  data-lang:           "en"
  crossorigin:         "anonymous"
